import 'package:analyzer/dart/ast/ast.dart';

import '../config/analyzer_config.dart';

/// Generates model boilerplate (copyWith, toMap, fromMap, ==, hashCode,
/// toString) from a class declaration's fields.
///
/// The generated code is wrapped in sentinel markers so it can be
/// regenerated idempotently.
class ModelGenerator {
  static const beginMarker =
      '// ── GENERATED BY DART SENTINEL ─────────────────────────────────────';
  static const endMarker =
      '// ── END GENERATED ──────────────────────────────────────────────────';

  final ModelsConfig config;

  const ModelGenerator(this.config);

  /// Generate all configured methods for a class.
  ///
  /// Returns the generated code block including markers.
  String generate({
    required String className,
    required List<FieldInfo> fields,
  }) {
    final buffer = StringBuffer();
    buffer.writeln();
    buffer.writeln('  $beginMarker');

    final effectiveFields = fields
        .where((f) => !f.isStatic)
        .toList();

    if (config.copyWithName.isNotEmpty) {
      _writeCopyWith(buffer, className, effectiveFields);
    }

    if (config.toMapName.isNotEmpty) {
      _writeToMap(buffer, className, effectiveFields);
    }

    if (config.fromMapName.isNotEmpty) {
      _writeFromMap(buffer, className, effectiveFields);
    }

    if (config.equality) {
      _writeEquality(buffer, className, effectiveFields);
    }

    if (config.toStringMethod) {
      _writeToString(buffer, className, effectiveFields);
    }

    buffer.writeln('  $endMarker');
    return buffer.toString();
  }

  /// Generate a complete model class from scratch.
  String generateFullClass({
    required String className,
    required List<FieldInfo> fields,
    bool constConstructor = true,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('class $className {');

    // Fields
    for (final field in fields) {
      buffer.writeln('  final ${field.type} ${field.name};');
    }
    buffer.writeln();

    // Constructor
    final keyword = constConstructor ? 'const ' : '';
    buffer.write('  ${keyword}$className({');
    for (final field in fields) {
      final required = field.isNullable ? '' : 'required ';
      buffer.write('${required}this.${field.name}, ');
    }
    buffer.writeln('});');

    // Generated methods
    buffer.write(generate(className: className, fields: fields));

    buffer.writeln('}');
    return buffer.toString();
  }

  /// Extract field info from a class declaration.
  static List<FieldInfo> extractFields(ClassDeclaration classDecl) {
    final fields = <FieldInfo>[];
    final body = classDecl.body;
    if (body is! BlockClassBody) return fields;
    for (final member in body.members) {
      if (member is! FieldDeclaration) continue;
      if (member.isStatic) continue;
      for (final variable in member.fields.variables) {
        final type = member.fields.type?.toSource() ?? 'dynamic';
        fields.add(FieldInfo(
          name: variable.name.lexeme,
          type: type,
          isNullable: type.endsWith('?'),
          isStatic: member.isStatic,
        ));
      }
    }
    return fields;
  }

  /// Update the generated section of an existing file.
  ///
  /// Returns the updated file content, or null if no changes were needed.
  String? updateGeneratedSection({
    required String fileContent,
    required String className,
    required List<FieldInfo> fields,
  }) {
    final beginIdx = fileContent.indexOf(beginMarker);
    final endIdx = fileContent.indexOf(endMarker);

    if (beginIdx == -1 || endIdx == -1) return null;

    final generated = generate(className: className, fields: fields);
    final endOfMarker = endIdx + endMarker.length;

    // Find the indentation-aware start (go back to beginning of line)
    var lineStart = beginIdx;
    while (lineStart > 0 && fileContent[lineStart - 1] != '\n') {
      lineStart--;
    }

    // Find end of marker line
    var lineEnd = endOfMarker;
    while (lineEnd < fileContent.length && fileContent[lineEnd] != '\n') {
      lineEnd++;
    }
    if (lineEnd < fileContent.length) lineEnd++; // include newline

    return fileContent.substring(0, lineStart) +
        generated +
        fileContent.substring(lineEnd);
  }

  // ── Private generators ─────────────────────────────────────────────

  void _writeCopyWith(
    StringBuffer buffer,
    String className,
    List<FieldInfo> fields,
  ) {
    final excludes = config.excludeFromCopyWith.toSet();
    final copyFields = fields.where((f) => !excludes.contains(f.name)).toList();

    buffer.write('  $className ${config.copyWithName}({');
    for (final f in copyFields) {
      final baseType = f.isNullable
          ? f.type
          : '${f.type}?';
      buffer.write('$baseType ${f.name}, ');
    }
    buffer.writeln('}) => $className(');
    for (final f in copyFields) {
      buffer.writeln('        ${f.name}: ${f.name} ?? this.${f.name},');
    }
    buffer.writeln('      );');
    buffer.writeln();
  }

  void _writeToMap(
    StringBuffer buffer,
    String className,
    List<FieldInfo> fields,
  ) {
    final excludes = config.excludeFromSerialization.toSet();
    final serFields = fields.where((f) => !excludes.contains(f.name)).toList();

    buffer.writeln('  Map<String, dynamic> ${config.toMapName}() => {');
    for (final f in serFields) {
      final value = _toMapValue(f);
      buffer.writeln("        '${f.name}': $value,");
    }
    buffer.writeln('      };');
    buffer.writeln();
  }

  void _writeFromMap(
    StringBuffer buffer,
    String className,
    List<FieldInfo> fields,
  ) {
    final excludes = config.excludeFromSerialization.toSet();
    final serFields = fields.where((f) => !excludes.contains(f.name)).toList();

    buffer.writeln(
      '  factory $className.${config.fromMapName}'
      '(Map<String, dynamic> map) => $className(',
    );
    for (final f in serFields) {
      final value = _fromMapValue(f);
      buffer.writeln("        ${f.name}: $value,");
    }
    buffer.writeln('      );');
    buffer.writeln();
  }

  void _writeEquality(
    StringBuffer buffer,
    String className,
    List<FieldInfo> fields,
  ) {
    buffer.writeln('  @override');
    buffer.writeln('  bool operator ==(Object other) =>');
    buffer.write('      identical(this, other) ||');
    buffer.writeln();
    buffer.write('      other is $className');
    for (final f in fields) {
      buffer.write(' && ${f.name} == other.${f.name}');
    }
    buffer.writeln(';');
    buffer.writeln();

    buffer.writeln('  @override');
    if (fields.isEmpty) {
      buffer.writeln('  int get hashCode => runtimeType.hashCode;');
    } else if (fields.length == 1) {
      buffer.writeln('  int get hashCode => ${fields.first.name}.hashCode;');
    } else {
      final args = fields.map((f) => f.name).join(', ');
      buffer.writeln('  int get hashCode => Object.hash($args);');
    }
    buffer.writeln();
  }

  void _writeToString(
    StringBuffer buffer,
    String className,
    List<FieldInfo> fields,
  ) {
    buffer.writeln('  @override');
    final params = fields.map((f) => '${f.name}: \$${f.name}').join(', ');
    buffer.writeln("  String toString() => '$className($params)';");
  }

  String _toMapValue(FieldInfo field) {
    final baseType = field.isNullable
        ? field.type.substring(0, field.type.length - 1)
        : field.type;

    if (_isListType(baseType)) return field.name;
    if (_isMapType(baseType)) return field.name;
    if (baseType == 'DateTime') {
      return field.isNullable
          ? '${field.name}?.toIso8601String()'
          : '${field.name}.toIso8601String()';
    }
    return field.name;
  }

  String _fromMapValue(FieldInfo field) {
    final baseType = field.isNullable
        ? field.type.substring(0, field.type.length - 1)
        : field.type;

    if (baseType == 'String') {
      return field.isNullable
          ? "map['${field.name}'] as String?"
          : "map['${field.name}'] as String";
    }
    if (baseType == 'int') {
      return field.isNullable
          ? "map['${field.name}'] as int?"
          : "map['${field.name}'] as int";
    }
    if (baseType == 'double') {
      return field.isNullable
          ? "map['${field.name}'] as double?"
          : "map['${field.name}'] as double";
    }
    if (baseType == 'bool') {
      return field.isNullable
          ? "map['${field.name}'] as bool?"
          : "map['${field.name}'] as bool";
    }
    if (baseType == 'DateTime') {
      return field.isNullable
          ? "map['${field.name}'] != null ? DateTime.parse(map['${field.name}'] as String) : null"
          : "DateTime.parse(map['${field.name}'] as String)";
    }
    if (_isListType(baseType)) {
      final inner = _extractGenericType(baseType);
      return "List<$inner>.from(map['${field.name}'] as List)";
    }
    if (_isMapType(baseType)) {
      return "Map<String, dynamic>.from(map['${field.name}'] as Map)";
    }
    return "map['${field.name}']";
  }

  bool _isListType(String type) =>
      type.startsWith('List<') || type == 'List';

  bool _isMapType(String type) =>
      type.startsWith('Map<') || type == 'Map';

  String _extractGenericType(String type) {
    final start = type.indexOf('<');
    final end = type.lastIndexOf('>');
    if (start == -1 || end == -1) return 'dynamic';
    return type.substring(start + 1, end);
  }
}

/// Information about a class field used for code generation.
class FieldInfo {
  final String name;
  final String type;
  final bool isNullable;
  final bool isStatic;

  const FieldInfo({
    required this.name,
    required this.type,
    this.isNullable = false,
    this.isStatic = false,
  });
}
